name: envied_lean_example
description: Envied Lean Builder example - demonstrating standalone generation without part files
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  envied: ^1.3.1

dev_dependencies:
  lean_builder: ^0.1.2
  envied_generator: 
    path: ../../packages/envied_generator
  lints: ^5.1.1
